version: '3'
services:

  laravel:
    image: gabrielmssantiago/laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx:
    image: gabrielmssantiago/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge