version: '3'
services:

  nodeserver:
    build:
      context: ./nodejs
    container_name: nodeserver
    networks:
      - node-network
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
  
networks:
  node-network:
    driver: bridge