version: '3'
services:

  nodeserver:
    build:
      context: ./nodejs
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    volumes:
      - ./nodejs:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
networks:
  node-network:
    driver: bridge